package exam.model.base;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysPaper<M extends BaseSysPaper<M>> extends BaseModel<M> {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}
	public void setUserNames(java.lang.String name) {
		set("user_names", name);
	}
	
	public java.lang.String getUserNames() {
		return getStr("user_names");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setRoleIds(java.lang.String roleIds) {
		set("role_ids", roleIds);
	}
	
	public java.lang.String getRoleIds() {
		return getStr("role_ids");
	}

	public void setUserIds(java.lang.String userIds) {
		set("user_ids", userIds);
	}
	
	public java.lang.String getUserIds() {
		return getStr("user_ids");
	}

	public void setKsTime(java.util.Date ksTime) {
		set("ks_time", ksTime);
	}
	
	public java.util.Date getKsTime() {
		return get("ks_time");
	}

	public void setJsTime(java.util.Date jsTime) {
		set("js_time", jsTime);
	}
	
	public java.util.Date getJsTime() {
		return get("js_time");
	}

	public void setDxtCount(java.lang.Integer dxtCount) {
		set("dxt_count", dxtCount);
	}
	
	public java.lang.Integer getDxtCount() {
		return getInt("dxt_count");
	}

	public void setDxtScore(java.math.BigDecimal dxtScore) {
		set("dxt_score", dxtScore);
	}
	
	public java.math.BigDecimal getDxtScore() {
		return get("dxt_score");
	}

	public void setDuoxtCount(java.lang.Integer duoxtCount) {
		set("duoxt_count", duoxtCount);
	}
	
	public java.lang.Integer getDuoxtCount() {
		return getInt("duoxt_count");
	}

	public void setDuoxtScore(java.math.BigDecimal duoxtScore) {
		set("duoxt_score", duoxtScore);
	}
	
	public java.math.BigDecimal getDuoxtScore() {
		return get("duoxt_score");
	}

	public void setPdtCount(java.lang.Integer pdtCount) {
		set("pdt_count", pdtCount);
	}
	
	public java.lang.Integer getPdtCount() {
		return getInt("pdt_count");
	}

	public void setPdtScore(java.math.BigDecimal pdtScore) {
		set("pdt_score", pdtScore);
	}
	
	public java.math.BigDecimal getPdtScore() {
		return get("pdt_score");
	}

	public void setTotalScore(java.math.BigDecimal totalScore) {
		set("total_score", totalScore);
	}
	
	public java.math.BigDecimal getTotalScore() {
		return get("total_score");
	}

	public void setCreateName(java.lang.String createName) {
		set("create_name", createName);
	}
	
	public java.lang.String getCreateName() {
		return getStr("create_name");
	}

}
