package exam.model.base;

import exam.model.SysRole;
import exam.model.SysUserInfo;
import exam.service.impl.UserInfoServiceImpl;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysUser<M extends BaseSysUser<M>> extends BaseModel<M> {

	
	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	public java.lang.String getPassword() {
		return getStr("password");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public  void setStatus(String status){
		set("status",status);
	}

	public String getStatus(){
		return get("status");
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}
	public java.lang.Integer getRoleId(){
		return getInt("role_id");
	}
	
	public void setRoleId(java.lang.Integer roleId){
         set("role_id",roleId);
	}

	
	public SysRole getRole(){
		Integer roleId = getRoleId();
		SysRole result = null;
		if(roleId != null){
			result = new SysRole().dao().findById(roleId);
		}
		if(result == null){
			result = new SysRole();
		}
		return result;
	}
	
	public SysUserInfo getUserInfo(){
		Integer userId = getId();
		SysUserInfo result= null;
		if(userId != null){
			result = new UserInfoServiceImpl().findUserInfoByUserId(userId);
		}
		if(result == null){
			result = new SysUserInfo();
		}
		return result;
	}
	
	
}
