package exam.model.base;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysPaperAnswer<M extends BaseSysPaperAnswer<M>> extends BaseModel<M>{

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}
	
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	public void setUserName(java.lang.String userName) {
		set("user_name", userName);
	}
	
	public java.lang.String getUserName() {
		return getStr("user_name");
	}

	public void setAnswer(java.lang.String answer) {
		set("answer", answer);
	}
	
	public java.lang.String getAnswer() {
		return getStr("answer");
	}

	public void setIsTrue(java.lang.Integer isTrue) {
		set("is_true", isTrue);
	}
	
	public java.lang.Integer getIsTrue() {
		return getInt("is_true");
	}

	public void setStId(java.lang.Integer stId) {
		set("st_id", stId);
	}
	
	public java.lang.Integer getStId() {
		return getInt("st_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
