package exam.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("sys_question", "id", SysQuestion.class);
		arp.addMapping("sys_role", "id", SysRole.class);
		arp.addMapping("sys_paper", "id", SysPaper.class);
		arp.addMapping("sys_score", "id", SysScore.class);
		arp.addMapping("sys_user", "id", SysUser.class);
		arp.addMapping("sys_user_info", "id", SysUserInfo.class);
		arp.addMapping("sys_access_log", "id", SysAccessLog.class);
		arp.addMapping("sys_paper_answer", "id", SysPaperAnswer.class);
		arp.addMapping("sys_paper_question", "id", SysPaperQuestion.class);
	}
}

