package exam.model;

import exam.model.base.BaseSysPaperQuestion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysPaperQuestion extends BaseSysPaperQuestion<SysPaperQuestion> {
	
}
