package exam.model;

import exam.model.base.BaseSysPaperAnswer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysPaperAnswer extends BaseSysPaperAnswer<SysPaperAnswer> {
	
}
